# 容器端口
server:
  port: 8090

# 定义应用程序版本号
application:
  version: Blurry World Beta

# 关闭 Thymeleaf 缓存
spring:
  thymeleaf:
    cache: false

# 图片上传路径
upload:
  file:
    path:
      storage: E:\\blurryworld\\file\\image\\
      host: http://localhost:${server.port}
