# 容器端口
server:
  port: 8090

# 定义应用程序版本号
application:
  version: Blurry World Beta

spring:
  # 关闭 Thymeleaf 缓存
  thymeleaf:
    cache: false
  # 配置数据源
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blurryworld?useUnicode=true&characterEncoding=utf-8

upload:
  # 图片上传路径
  file:
    path:
      storage: E:\\blurryworld\\file\\image\\
      host: http://localhost:${server.port}
  # 头像上传路径
  avatar:
    path:
      storage: E:\\blurryworld\\file\\avatar\\
      host: http://localhost:${server.port}

# MyBatis
mybatis:
  type-aliases-package: com.moodright.blurryworld.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml




